apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port  | int }}
      targetPort: {{ .Values.service.targetPort | int }}
      nodePort: 30080
  selector:
    app: {{ .Chart.Name }}
